### ISSUE TITLE
Successfully installed UNKNOWN-2.1.12.dev3+g86c9b95

### ISSUE THREAD

**Issue by jielab** [23andMe/yhaplo#38] opened 2024-05-30 23:51 UTC
Hi, there:

I found that **git clone https://github.com/23andMe/yhaplo.git** works, while 
**git clone git@github.com:23andMe/yhaplo.git** did NOT work. Don't know if other users encountered the same issue.
![image](https://github.com/23andMe/yhaplo/assets/26947455/5f02610f-8e31-4cb2-9f6b-3520dafbb91c)

Please see the screenshot below. The command **pip install --editable .** did not give me any error message, but I could not find a program named **yhaplo** or **UNKNOWN-2.1.12.dev3+g86c9b95**.
![image](https://github.com/23andMe/yhaplo/assets/26947455/f035f80a-9ba8-4c26-84be-6170851afce0)

Can you please help?

Thanks!

Jie

**Comment by dpoznik** [comment] 2024-05-31 01:12
> I found that `git clone https://github.com/23andMe/yhaplo.git` works,
> while`git clone git@github.com:23andMe/yhaplo.git` did NOT work.

Here are GitHub's instructions on how to connect via SSH:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh

SSH is generally preferred, but if you don't want to set that up, I think it should be fine, but slower, to clone the repo over HTTPS.

As to your second question, I'm guessing the issue is related to your use of `sudo`. With `sudo`, perhaps the `yhaplo` executable is getting installed only for the root user. I suggest issuing the `pip install` command without `sudo`.

**Comment by jielab** [comment] 2024-06-01 10:09
Thanks!

But I still got an error without using "sudo". Please see the screenshot below.

![image](https://github.com/23andMe/yhaplo/assets/26947455/2a2761e1-ceaf-4e12-9509-156a85986a17)

**Comment by dpoznik** [comment] 2024-06-03 16:46
The version of `setuptools` you are using is pretty old. Try:
```sh
pip install --upgrade setuptools
```

**Comment by jielab** [comment] 2024-06-04 15:51
Thanks!

But please see the screenshot below. It still does not work.
It shows **ERROR: setuptools==59.6.0 is used in combination with setuptools_scm>=8.x**

Best regards,
Jie

![image](https://github.com/23andMe/yhaplo/assets/26947455/8790305d-4961-4a98-8850-1d58b606b629)

**Comment by dpoznik** [comment] 2024-06-04 18:01
It looks like you have upgraded `setuptools` to 70.0.0 in your user environment, `~/.local/lib/python3.10/site-packages`, but when you attempt to install Yhaplo, the build system is using version 59.6.0, despite the fact that we require version 64 or greater: https://github.com/23andMe/yhaplo/blob/86c9b9553178d038f435e6705b94f8556714b5b6/pyproject.toml#L2

I don't have great insight into how your environment is set up, but you may have better luck in a dedicated virtual environment:
```
python -m venv ~/venvs/yhaplo
source ~/venvs/yhaplo/bin/activate
pip install --upgrade pip setuptools
cd /path/to/yhaplo
pip install --editable .
```
Then you can use Yhaplo whenever that environment is activated and do `deactivate` to deactivate.

I think the virtual environment approach would probably be best, but some other things that may be helpful, in arbitrary order:
- After changing directory to your Yhaplo clone, do `which pip`. Does this match the Python environment you're expecting?
- `pip show setuptools | grep Version`
- `sudo pip install --upgrade setuptools`

**Comment by jielab** [comment] 2024-06-05 01:27
Ok, thank you so much!

I am using the Ubuntu 22.04.3.LTS coming with Windows 11. 
I will try to resolve this installation issue myself.

Just wondering: is there a way to make yhaplo analyze Mitochondrial DNA to build phylogenetic trees for females?

Thanks!
Jie

**Comment by dpoznik** [comment] 2024-06-05 01:35
OK, sounds good; good luck. I am willing to bet that installing into a virtual environment will work for you. I will go ahead and close the Issue, but feel free to follow up if you learn anything interesting.

Although the underlying principle is the same, it would be nontrivial to adapt Yhaplo for use on mtDNA.
Haplogrep is a good tool for MT haplogroups: https://haplogrep.readthedocs.io/en/latest/installation/

**Closed by dpoznik** 2024-06-05 01:35 UTC
